---
- name: format volume for /opt
  filesystem: fstype=xfs dev=/dev/xvdf

- name: install PPA for ec2-consistent-snapshots
  apt_repository: repo='ppa:ppa:alestic'
  
- name: update apt cache for PPA
  apt: update_cache=yes
  
- name: install ec2-consistent-snapshots
  apt: name=ec2-consistent-snapshots state=present
  
- name: check filesystem
  command: file -sL /dev/xvdf
  register: fstype

- name: look at results
  debug: var=fstype

- name: mount volume at /opt
  mount: name=/opt src=/dev/xvdf fstype=xfs state=present

  