---
- name: update apt cache
  apt: update_cache=yes

- name: upgrade apt packages
  apt: upgrade=full

- name: create install group
  sudo: yes
  group: name={{ install_group }} state=present

- name: create install user
  sudo: yes
  user: name={{ install_user }} group={{ install_group }} shell=/bin/bash createhome=yes state=present

- name: chown /opt
  file: owner={{ install_user }} group={{ install_group }} state=directory path=/opt

- name: create install directory
  file: owner={{ install_user }} group={{ install_group }} state=directory path=/opt/install
