---
- name: update apt cache
  apt: update_cache=yes

- name: upgrade apt packages
  apt: upgrade=full

- name: chown /opt
  file: owner=vagrant group=vagrant state=directory path=/opt

- name: create install directory
  file: owner=vagrant group=vagrant state=directory path=/opt/install

