---
- name: update apt cache
  apt: update_cache=yes

- name: upgrade apt packages
  apt: upgrade=full

- name: chown /opt
  file: owner=vagrant group=vagrant state=directory path=/opt

- name: create install directory
  file: owner=vagrant group=vagrant state=directory path=/opt/install

- name: sufia / general server prerequisites
  apt: name={{ item}} state=latest
  with_items:
    - imagemagick
    - redis-server
    #- libsqlite3-dev
    #- sqlite3
    - git
    - nodejs
    - unzip
    #- poppler-utils # not mentioned in sufia; ualberta uses
    #- libreoffice-headless # not mentioned in sufia; ualberta uses
    #- libreoffice # not mentioned in sufia; ualberta uses
    #- GraphicsMagick # not mentioned in sufia; ualberta uses

