---
- name: install zip utility
  sudo: yes
  apt: name=unzip state=present

- name: download fits zip
  get_url: url=http://projects.iq.harvard.edu/files/fits/files/fits-0.8.4.zip group=vagrant owner=vagrant dest={{ install_path }}/fits-0.8.4.zip
  sudo: no

- name: unpack fits
  sudo: no
  unarchive: src={{ install_path }}/fits-0.8.4.zip dest={{ install_path }}/ creates={{ install_path }}/fits-0.8.4/fits.sh copy=no

- name: make fits executable
  sudo: no
  file: path={{ install_path }}/fits-0.8.4/fits.sh mode=0755

- name: copy fits
  sudo: yes
  shell: cp -r {{ install_path }}/fits-0.8.4/* /usr/local/bin/

- name: symlink fits
  sudo: yes
  file: src=/usr/local/bin//fits.sh dest=/usr/local/bin/fits state=link

