---
# adapted from
# https://github.com/akishin/ansible-playbooks/blob/master/lokka/roles/passenger/tasks/main.yml

- name: install passenger gem
  gem: name=passenger state=present # version=$passenger_ver

- name: install apache packages
  apt: name={{ item }} state=latest
  with_items:
    - apache2-prefork-dev
    - apache2-mpm-worker

- name: install passenger-install-apache2-module
  sudo: yes
  shell: passenger-install-apache2-module --auto creates=/usr/lib/ruby/gems/2.2.0/gems/passenger-{{ passenger_ver }}/buildout/apache2/mod_passenger.so

- name: generate passenger.conf file
  shell: passenger-install-apache2-module --snippet > /etc/apache2/conf-available/passenger.conf
  
- name: symlink passenger config
  shell: ln -s /etc/apache2/conf-available/passenger.conf /etc/apache2/conf-enabled/passenger.conf
  sudo: yes
  
- name: restart apache
  service: name=apache2 state=restarted
  